### ISSUE TITLE
250 letter limit

### ISSUE THREAD

**Issue by Aavild** [Aavild/NewTerminal#1]
This [throw](https://github.com/Aavild/NewTerminal/blob/c74a6f7087e93dc022703d85eee63b9a8805cc5c/Patch/TerminalStartPatch.cs#L59) is untested for whether 240 letters is the actual limit. 

The code actually says the limit is 250 with everything included, but maybe already beyond 100 letters it is outside the terminal? 

Or maybe a lot of letters is added later on?

**Comment by LynxBites** [comment]
Hi, I just straight up removed limit by setting it to 9999 and everything works fine, here is a string with 2000+ characters in it.
![image_2023-11-30_181428571](https://github.com/Aavild/NewTerminal/assets/78800052/a24f1b0b-0e6e-4ff0-a48b-cca96b4c176e)

**Comment by Aavild** [comment]
I've tested this further by counting characters in increments of 51 as this equals a single line in the terminal

here is an example of a terminal containing exactly 4794 characters:
![image](https://github.com/Aavild/NewTerminal/assets/46568674/5e11ddd3-4a74-4375-9f6b-a7cbfb04d63a)
![image](https://github.com/Aavild/NewTerminal/assets/46568674/3ece5ffa-fd43-477f-a2aa-77b3d1331cf9)
![image](https://github.com/Aavild/NewTerminal/assets/46568674/36435962-eb9a-4d05-8b02-71d77279e7bb)
![image](https://github.com/Aavild/NewTerminal/assets/46568674/061a75ab-dbec-4b5f-a61e-23a5f7850f9d)

and here is a terminal with exactly 4845:
![image](https://github.com/Aavild/NewTerminal/assets/46568674/9813cc52-fbb0-4516-a59b-a85ef4a8be29)
![image](https://github.com/Aavild/NewTerminal/assets/46568674/6b15044e-1d74-4e79-9b41-8f8f8b525830)
![image](https://github.com/Aavild/NewTerminal/assets/46568674/e762287e-e038-4921-ac0a-71b050e74d21)
![image](https://github.com/Aavild/NewTerminal/assets/46568674/2afe1bea-669e-4c53-84a7-0b8ab7072416)

Notice that with 4845 characters that 1122 and 3621 are unreadable. therefore the max amount of characters should be 4794 characters
