### ISSUE TITLE
Text replacement only works in submenus

### ISSUE THREAD

**Issue by Sidiusz** [Aavild/NewTerminal#8]
For some reason (for example) in the HELP or OTHER and other menus the text is not replaced, while everything is replaced in the submenus (screenshots)

![image](https://github.com/Aavild/NewTerminal/assets/20544939/9b92b05c-5b1f-4c40-a2ed-900bac8b0816)
![image](https://github.com/Aavild/NewTerminal/assets/20544939/c826c40d-747a-40f0-b604-8f8d17221009)
![image](https://github.com/Aavild/NewTerminal/assets/20544939/c8b7d7a7-4658-4678-a9a6-66a7083e92ea)

**Comment by Aavild** [comment]
whoops wrong linked issue in PR

**Comment by Aavild** [comment]
Note that `TerminalMenus.Special` is the terminal display when opening the terminal. If you want to modify the output of typing the `help` command you need to find it in `NewTerminal-Other`
